/**
 * PDF Report Generation Utilities
 * Uses PDFKit to generate PDFs for reports
 */

const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

const uploadsDir = path.join(__dirname, '../uploads');

/**
 * Generate a shipment summary PDF report
 * @param {object} shipmentData - Shipment data with related containers and documents
 * @returns {Promise<string>} Path to generated PDF file
 */
const generateShipmentReportPDF = async (shipmentData) => {
  return new Promise((resolve, reject) => {
    try {
      const filename = `shipment-report-${shipmentData.id}-${Date.now()}.pdf`;
      const filepath = path.join(uploadsDir, filename);

      const doc = new PDFDocument({
        size: 'A4',
        margin: 40,
      });

      const stream = fs.createWriteStream(filepath);

      doc.pipe(stream);

      // Title
      doc.fontSize(20).font('Helvetica-Bold').text('Shipment Report', { align: 'center' });
      doc.moveDown(0.5);
      doc.fontSize(10).font('Helvetica').text(`Generated on: ${new Date().toLocaleDateString()}`, { align: 'center' });
      doc.moveDown(1);

      // Shipment Details Section
      doc.fontSize(12).font('Helvetica-Bold').text('Shipment Details');
      doc.fontSize(10).font('Helvetica');

      doc.text(`Tracking Number: ${shipmentData.tracking_number}`);
      doc.text(`Vessel Name: ${shipmentData.vessel_name || 'N/A'}`);
      doc.text(`Origin: ${shipmentData.origin}`);
      doc.text(`Destination: ${shipmentData.destination}`);
      doc.text(`Status: ${shipmentData.status.toUpperCase()}`);
      doc.text(`Estimated Arrival: ${shipmentData.estimated_arrival || 'N/A'}`);
      doc.text(`Actual Arrival: ${shipmentData.actual_arrival || 'Pending'}`);
      doc.text(`Created By: ${shipmentData.created_by_name || 'System'}`);
      doc.text(`Created At: ${new Date(shipmentData.created_at).toLocaleDateString()}`);

      doc.moveDown(1);

      // Containers Section
      if (shipmentData.containers && shipmentData.containers.length > 0) {
        doc.fontSize(12).font('Helvetica-Bold').text('Associated Containers');
        doc.fontSize(10).font('Helvetica');

        shipmentData.containers.forEach((container, index) => {
          doc.text(`Container ${index + 1}: ${container.container_number}`);
          doc.text(`  Type: ${container.type} | Weight: ${container.weight_kg || 'N/A'} kg | Status: ${container.status}`);
        });

        doc.moveDown(0.5);
      }

      // Documents Section
      if (shipmentData.documents && shipmentData.documents.length > 0) {
        doc.fontSize(12).font('Helvetica-Bold').text('Associated Documents');
        doc.fontSize(10).font('Helvetica');

        shipmentData.documents.forEach((doc_item, index) => {
          doc.text(`${index + 1}. ${doc_item.doc_type} - ${doc_item.file_name}`);
        });

        doc.moveDown(0.5);
      }

      // Footer
      doc.fontSize(8).font('Helvetica').text('Generated by MaritimeFlow System', { align: 'center' });

      // Finalize PDF
      doc.end();

      stream.on('finish', () => {
        resolve(`/uploads/${filename}`);
      });

      stream.on('error', (err) => {
        reject(err);
      });
    } catch (err) {
      reject(err);
    }
  });
};

/**
 * Generate a container status report PDF
 * @param {array} containersData - Array of container data
 * @returns {Promise<string>} Path to generated PDF file
 */
const generateContainerReportPDF = async (containersData) => {
  return new Promise((resolve, reject) => {
    try {
      const filename = `container-report-${Date.now()}.pdf`;
      const filepath = path.join(uploadsDir, filename);

      const doc = new PDFDocument({
        size: 'A4',
        margin: 40,
      });

      const stream = fs.createWriteStream(filepath);

      doc.pipe(stream);

      // Title
      doc.fontSize(20).font('Helvetica-Bold').text('Container Status Report', { align: 'center' });
      doc.moveDown(0.5);
      doc.fontSize(10).font('Helvetica').text(`Generated on: ${new Date().toLocaleDateString()}`, { align: 'center' });
      doc.moveDown(1);

      // Summary Statistics
      const statusCounts = {};
      containersData.forEach((container) => {
        statusCounts[container.status] = (statusCounts[container.status] || 0) + 1;
      });

      doc.fontSize(12).font('Helvetica-Bold').text('Summary');
      doc.fontSize(10).font('Helvetica');
      doc.text(`Total Containers: ${containersData.length}`);

      Object.entries(statusCounts).forEach(([status, count]) => {
        doc.text(`  ${status.replace(/_/g, ' ').toUpperCase()}: ${count}`);
      });

      doc.moveDown(1);

      // Container Table
      doc.fontSize(12).font('Helvetica-Bold').text('Container Details');
      doc.moveDown(0.5);

      // Table headers
      const tableTop = doc.y;
      doc.fontSize(9).font('Helvetica-Bold');
      doc.text('Container#', 50, tableTop);
      doc.text('Type', 150, tableTop);
      doc.text('Weight (kg)', 230, tableTop);
      doc.text('Status', 330, tableTop);

      doc.fontSize(9).font('Helvetica');
      let y = tableTop + 20;

      containersData.forEach((container) => {
        if (y > 700) {
          doc.addPage();
          y = 40;
        }

        doc.text(container.container_number, 50, y);
        doc.text(container.type, 150, y);
        doc.text(container.weight_kg || 'N/A', 230, y);
        doc.text(container.status, 330, y);

        y += 20;
      });

      doc.moveDown(2);

      // Footer
      doc.fontSize(8).font('Helvetica').text('Generated by MaritimeFlow System', { align: 'center' });

      // Finalize PDF
      doc.end();

      stream.on('finish', () => {
        resolve(`/uploads/${filename}`);
      });

      stream.on('error', (err) => {
        reject(err);
      });
    } catch (err) {
      reject(err);
    }
  });
};

/**
 * Generate a daily summary report PDF
 * @param {object} summaryData - Contains shipments_summary, containers_summary, documents_count
 * @returns {Promise<string>} Path to generated PDF file
 */
const generateSummaryReportPDF = async (summaryData) => {
  return new Promise((resolve, reject) => {
    try {
      const filename = `summary-report-${Date.now()}.pdf`;
      const filepath = path.join(uploadsDir, filename);

      const doc = new PDFDocument({
        size: 'A4',
        margin: 40,
      });

      const stream = fs.createWriteStream(filepath);

      doc.pipe(stream);

      // Title
      doc.fontSize(20).font('Helvetica-Bold').text('Daily Summary Report', { align: 'center' });
      doc.moveDown(0.5);
      doc.fontSize(10).font('Helvetica').text(`Generated on: ${new Date().toLocaleDateString()}`, { align: 'center' });
      doc.moveDown(1);

      // Shipments Summary
      if (summaryData.shipments_summary) {
        doc.fontSize(12).font('Helvetica-Bold').text('Shipments Overview');
        doc.fontSize(10).font('Helvetica');

        doc.text(`Total Shipments: ${summaryData.shipments_summary.total || 0}`);
        doc.text(`Pending: ${summaryData.shipments_summary.pending || 0}`);
        doc.text(`In Transit: ${summaryData.shipments_summary.in_transit || 0}`);
        doc.text(`Arrived: ${summaryData.shipments_summary.arrived || 0}`);
        doc.text(`Delivered: ${summaryData.shipments_summary.delivered || 0}`);
        doc.text(`Cancelled: ${summaryData.shipments_summary.cancelled || 0}`);

        doc.moveDown(1);
      }

      // Containers Summary
      if (summaryData.containers_summary) {
        doc.fontSize(12).font('Helvetica-Bold').text('Containers Overview');
        doc.fontSize(10).font('Helvetica');

        doc.text(`Total Containers: ${summaryData.containers_summary.total || 0}`);
        doc.text(`At Sea: ${summaryData.containers_summary.at_sea || 0}`);
        doc.text(`At Port: ${summaryData.containers_summary.at_port || 0}`);
        doc.text(`Under Inspection: ${summaryData.containers_summary.under_inspection || 0}`);
        doc.text(`Cleared: ${summaryData.containers_summary.cleared || 0}`);
        doc.text(`Released: ${summaryData.containers_summary.released || 0}`);

        doc.moveDown(1);
      }

      // Documents Summary
      if (summaryData.documents_count !== undefined) {
        doc.fontSize(12).font('Helvetica-Bold').text('Documents');
        doc.fontSize(10).font('Helvetica');
        doc.text(`Total Documents: ${summaryData.documents_count}`);

        doc.moveDown(1);
      }

      // Footer
      doc.fontSize(8).font('Helvetica').text('Generated by MaritimeFlow System', { align: 'center' });

      // Finalize PDF
      doc.end();

      stream.on('finish', () => {
        resolve(`/uploads/${filename}`);
      });

      stream.on('error', (err) => {
        reject(err);
      });
    } catch (err) {
      reject(err);
    }
  });
};

module.exports = {
  generateShipmentReportPDF,
  generateContainerReportPDF,
  generateSummaryReportPDF,
};
